remote: true

experienceLevel:
  internship: true
  entry: true
  associate: false
  mid-senior level: false
  director: false
  executive: false

jobTypes:
  full-time: true
  contract: false
  part-time: false
  temporary: false
  internship: true
  other: false
  volunteer: false

date:
  all time: false
  month: false
  week: false
  24 hours: true

positions:
  - Software engineer

locations:
  - United States

apply_once_at_company: true

distance: 100

company_blacklist:
  - Apple
  - Meta
  - Google
  - Microsoft
  - Amazon
  - Tesla
  - SpaceX
  - Tesla
  - Netflix

title_blacklist:
  - word1
  - word2

job_applicants_threshold:
  min_applicants: 0
  max_applicants: 100000

llm_model_type: openai
llm_model: 'gpt-4o-mini'
# llm_api_url: https://api.pawan.krd/cosmosrp/v1'
